// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcectuiohvwzxywrcyce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjZWN0dWlvaHZ3enh5d3JjeWNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMzQ0NTIsImV4cCI6MjA2NjkxMDQ1Mn0.x5xYxbwgvLyom0xcZTRvOxyiVtuzxSTv4GY4XmETVHU";

export { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY };

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});